name: Actualisation hebdomadaire des données CAC 40

on:
  schedule:
    # Se lance tous les lundis à 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch: # Permet de lancer le scrapper manuellement via le bouton "Run workflow"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🐍 Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 📦 Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📊 Scrapping des prix de clôture
        run: python scrapper_yfinance_cours.py

      - name: 🏢 Scrapping des fondamentaux (macro)
        run: python scrapper_yfinance_macro.py

      - name: 💾 Sauvegarde des données sur GitHub
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add historique/*.csv
          git commit -m "Mise à jour auto des données : $(date +'%d/%m/%Y')" || echo "Aucune modification à commiter"
          git push

      - name: 🚀 Notification à Render
        run: curl -X POST "https://api.render.com/deploy/srv-d6tamkv5gffc7391ngdg?key=GtujNavkxWk"
